### ISSUE TITLE
include expiring date alerts on quota bar when expires in <15 days

### ISSUE THREAD

**Issue by liusiqi43** [rezometz/paiji2#17]

**Comment by David-5-1** [comment]
If you want to do this quickly, I can tweak rezo.rez pages/quotasDetail/IP page to output this data in an easy to parse format (rather than HTML…) since I don't think it is no longer in use (without paiji1).

Even if it is not maybe the cleanest way to do it, I prefer using rezo.rez to get all needed data about members rather than using a direct DB access that will be dependent on rezo.rez DB structure.

**Comment by gpichot** [comment]
Actually we already have the abstraction layer implemented (I used the command inspectdb). So technically we already have of the interface required to work on it. Only for now a large part of it is commented and need to be rewritten to properly implement associations (IntegerField -> ForeignKey, english naming conventions). See this file:

https://github.com/rezometz/paiji2/blob/master/rezo/models.py

I would like to avoid an API request and prefer to hit the DB. Actually the API solution will involve more work (my development environment is set up with a local rezo.rez DB clone).

The best way to go is to add a new method named expire_on to the Utilisateur object that implements it (using also cached_property decorator). In the future if we want to add a expire_on field to rezo.rez, migration will be easier (no need to change anything in templates).

FYI, the account used by Paiji for the rezo,rez DB is a read-only one.
