### ISSUE TITLE
Language & Internationalization

### ISSUE THREAD

**Issue by gpichot** [rezometz/paiji2#31]
UI texts are a mix of French and English. We have to decide which one to use and then use it everywhere with i18n functions (trans, blocktrans etc...).

**Comment by LGD-Fr** [comment]
I think we must let the strings in the *code* in *english*, and then use the i18n (makemessages/compilemessages) module to translate in latine(hi @luc--  :-))/french/german/russian/chinese/what-you-want in order to enable the user to choose his preferred language (with a little "select" forum at the top of our beloved site)
See django-paiji-forum and his sample project to have an example.

**Comment by gpichot** [comment]
Yap, just a little addition, there is also the `<link rel="alternate" ... />` element to add for each language and on each page (as the `lang` attribute).

**Comment by LGD-Fr** [comment]
done
